### ISSUE TITLE
no issue please Read

### ISSUE THREAD

**Issue by ghost** [jarne/Chat#4]
Hi Jarne,

zuerst: Das ist kein Issue, ich fand leider keinen Anderen Weg mit dir Kontakt aufzubauen. Du hast ja vor geraumer Zeit, den surva server beendet. Das ist die eine Sache. Heute habe ich aus Spaß wieder mal nach dem Server gegoogelt und bin aufs GitHub gestoßen. Wie es aussieht entwickelst du immer noch für PocketMine. Läuft bei dir zur Zeit ein Server?

Gruß, 

Computerfreund

Vielleicht kennst du mich noch, ich war die nervigste Person im Support :p

**Comment by jarne** [comment]
Hey,

aktuell entwickle ich nur noch die PocketMine-Plugins unter https://github.com/survanetwork weiter, Server betreibe ich im Moment keine mehr.

Möglicherweise in Zukunft mal wieder, vielleicht wenn sich mit der Server-Software seitens Mojang / Microsoft etwas weiterentwickeln sollte, im Bereich Mod-Support - könnte aber noch (ein paar Jahre) dauern 😉.

Kenne dich natürlich noch aus dem Support 😄.

Viele Grüße
Jarne
